name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write
    
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: creality-slicer-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4
      
      - name: installer
        shell: cmd
        run: |
          curl https://file2-cdn.creality.com/file/cbf0359e500409d3320b370dc8602813/Creality_Slicer-4.8.2-build-291-win64.exe -L --output installer.exe &&^
          7z x installer.exe -o"installation" -y &&^
          rmdir /q /s "arduino" &&^
          rmdir /q /s "$PLUGINSDIR" &&^
          cd installation &&^
          dir
          
      - shell: cmd
        run: xcopy /H /Y /C "CrealitySlicer.exe.Portable.cmd" "installation"
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "installation"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "installation/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
